name: never_flutter_sample_code
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  uuid: ^3.0.7
  extended_nested_scroll_view: ^6.1.0
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic_mono: ^1.22.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  freezed: ^2.3.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fixture_data/
